# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title: Benjamin Hopfer Software Solutions
email: contact@benjaminhopfer.com
description: Problems and solutions of a freelancing software engineer
baseurl: ""
url: "https://benjaminhopfer.com"
github_username: b3ret
# logo: assets/img/logo.png
show_downloads: false

# Build settings
#
theme: jekyll-theme-minimal
# plugins:
  # - jekyll-feed

# Exclude from processing.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
